import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import ExerciseSelector from '../components/ExerciseSelector/ExerciseSelector'
import ExerciseCard from '../components/ExerciseCard/ExerciseCard'
import useExercises from '../hooks/useExercises'
import { createWorkout } from '../services/workoutService'

const today=()=>new Date().toLocaleDateString('en-CA')
const blankSet=()=>({localId:crypto.randomUUID(),reps:'',weight:'',durationSeconds:''})

export default function NewWorkoutPage(){
  const navigate=useNavigate();const {exercises,loading,error,addExercise}=useExercises();const [items,setItems]=useState([]);const [date,setDate]=useState(today());const [saving,setSaving]=useState(false);const [saveError,setSaveError]=useState('');const [showCreate,setShowCreate]=useState(false);const [newExercise,setNewExercise]=useState({name:'',metricType:'reps'})
  const add=ex=>setItems(current=>[...current,{exerciseId:ex.id,name:ex.name,metricType:ex.metricType,sets:[blankSet()]}])
  const patchItem=(index,fn)=>setItems(current=>current.map((item,i)=>i===index?fn(item):item))
  async function createNew(e){e.preventDefault();try{const ex=await addExercise(newExercise);add(ex);setNewExercise({name:'',metricType:'reps'});setShowCreate(false)}catch(err){setSaveError(err.message)}}
  function valid(){return items.length>0&&items.every(item=>item.sets.length>0&&item.sets.every(s=>item.metricType==='duration'?s.durationSeconds!=='' : item.metricType==='weight_reps'?s.weight!==''&&s.reps!=='' : s.reps!==''))}
  async function save(){if(!valid())return setSaveError('Add at least one complete set for every exercise.');try{setSaving(true);setSaveError('');const id=await createWorkout({performedAt:`${date}T12:00:00`,exercises:items});navigate(`/workouts/${id}`,{state:{saved:true}})}catch(err){setSaveError(err.message)}finally{setSaving(false)}}
  return <section className="page"><p className="eyebrow">New session</p><h1 className="page-title">Build your workout</h1><div className="field date-field"><label htmlFor="performed">Workout date</label><input id="performed" type="date" value={date} onChange={e=>setDate(e.target.value)}/></div>{error&&<p className="status error">{error}</p>}{loading?<p className="status">Loading exercises…</p>:<><ExerciseSelector exercises={exercises} disabledIds={items.map(x=>x.exerciseId)} onAdd={add}/><button className="new-exercise-toggle" type="button" onClick={()=>setShowCreate(x=>!x)}>{showCreate?'Cancel':'+ Create a new exercise'}</button>{showCreate&&<form className="create-exercise card" onSubmit={createNew}><div className="field"><label htmlFor="new-name">Exercise name</label><input id="new-name" value={newExercise.name} onChange={e=>setNewExercise({...newExercise,name:e.target.value})} required/></div><div className="field"><label htmlFor="metric">Tracking type</label><select id="metric" value={newExercise.metricType} onChange={e=>setNewExercise({...newExercise,metricType:e.target.value})}><option value="reps">Reps</option><option value="weight_reps">Weight + reps</option><option value="duration">Duration</option></select></div><button className="secondary-button" type="submit">Create & add</button></form>}</>}<div className="stack workout-builder">{items.map((item,i)=><ExerciseCard key={item.exerciseId} item={item} onAddSet={()=>patchItem(i,x=>({...x,sets:[...x.sets,blankSet()]}))} onRemoveSet={setIndex=>patchItem(i,x=>({...x,sets:x.sets.filter((_,j)=>j!==setIndex)}))} onUpdateSet={(setIndex,key,value)=>patchItem(i,x=>({...x,sets:x.sets.map((s,j)=>j===setIndex?{...s,[key]:value}:s)}))} onRemove={()=>setItems(x=>x.filter((_,j)=>j!==i))}/>)}</div>{!items.length&&!loading&&<div className="empty-state"><p className="muted">Choose an exercise above to start logging sets.</p></div>}{saveError&&<p className="status error">{saveError}</p>}<button className="primary-button full-width" type="button" disabled={saving||!items.length} onClick={save}>{saving?'Saving workout…':'Save workout'}</button></section>}
